version: '3.7'

services:
  testmslog:
    image: testmslog:190129
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: testmslog
    volumes:
      - /home/testmslog:/home/testmslog
    restart: unless-stopped